apiVersion: v1
kind: Namespace
metadata:
  name: payment-demo
  labels:
    demo: ztwim-protected
    security.openshift.io/scc.podSecurityLabelSync: "false"
  annotations:
    # Enable SPIRE injection for workloads in this namespace
    spire.openshift.io/inject: "true"
